[package]
name = "quantum"
version = "0.1.0"
description = "Quantum - A modern code editor built with Tauri + React + TypeScript"
authors = ["Bhavin"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "quantum_lib"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
regex = "1"
notify = "8"
dirs = "6"
portable-pty = "0.9"
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
debug = false
