import type { ThemeDefinition } from "@/types/theme";

const darkTokenColors: ThemeDefinition["tokenColors"] = [];

const lightTokenColors: ThemeDefinition["tokenColors"] = [];

const catppuccinTokenColors: ThemeDefinition["tokenColors"] = [];

export const BUILTIN_THEMES: ThemeDefinition[] = [
  {
    name: "dark",
    type: "dark",
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#e6edf3",
      "editor.lineHighlightBackground": "#161b22",
      "editor.selectionBackground": "#264f78",
      "editorCursor.foreground": "#58a6ff",
      "editorLineNumber.foreground": "#6e7681",
      "editorLineNumber.activeForeground": "#e6edf3",
      "editorIndentGuide.background1": "#21262d",
      "editorIndentGuide.activeBackground1": "#30363d",
      "editorWidget.background": "#161b22",
      "editorWidget.border": "#30363d",
      "editorSuggestWidget.background": "#161b22",
      "editorSuggestWidget.border": "#30363d",
      "editorSuggestWidget.selectedBackground": "#1f6feb33",
      "terminal.background": "#0d1117",
      "terminal.foreground": "#e6edf3",
      "terminal.cursor": "#58a6ff",
      "terminal.cursorAccent": "#0d1117",
      "terminal.selectionBackground": "#264f78",
      "terminal.ansiBlack": "#0d1117",
      "terminal.ansiRed": "#ff7b72",
      "terminal.ansiGreen": "#7ee787",
      "terminal.ansiYellow": "#d2a8ff",
      "terminal.ansiBlue": "#79c0ff",
      "terminal.ansiMagenta": "#ff7b72",
      "terminal.ansiCyan": "#56d4dd",
      "terminal.ansiWhite": "#e6edf3",
      "terminal.ansiBrightBlack": "#6e7681",
      "terminal.ansiBrightRed": "#ffa198",
      "terminal.ansiBrightGreen": "#a5d6a2",
      "terminal.ansiBrightYellow": "#d2a8ff",
      "terminal.ansiBrightBlue": "#a5d6ff",
      "terminal.ansiBrightMagenta": "#ffa198",
      "terminal.ansiBrightCyan": "#9cdbff",
      "terminal.ansiBrightWhite": "#f0f6fc",
    },
    tokenColors: darkTokenColors,
    terminal: {
      background: "#0d1117",
      foreground: "#e6edf3",
      cursor: "#58a6ff",
      cursorAccent: "#0d1117",
      selectionBackground: "#264f78",
      black: "#0d1117",
      red: "#ff7b72",
      green: "#7ee787",
      yellow: "#d2a8ff",
      blue: "#79c0ff",
      magenta: "#ff7b72",
      cyan: "#56d4dd",
      white: "#e6edf3",
      brightBlack: "#6e7681",
      brightRed: "#ffa198",
      brightGreen: "#a5d6a2",
      brightYellow: "#d2a8ff",
      brightBlue: "#a5d6ff",
      brightMagenta: "#ffa198",
      brightCyan: "#9cdbff",
      brightWhite: "#f0f6fc",
    },
  },
  {
    name: "light",
    type: "light",
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#1f2328",
      "editor.lineHighlightBackground": "#f6f8fa",
      "editor.selectionBackground": "#0969da33",
      "editorCursor.foreground": "#0969da",
      "editorLineNumber.foreground": "#8c959f",
      "editorLineNumber.activeForeground": "#1f2328",
      "editorIndentGuide.background1": "#eaeef2",
      "editorIndentGuide.activeBackground1": "#d0d7de",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#1f2328",
      "terminal.cursor": "#0969da",
      "terminal.cursorAccent": "#ffffff",
      "terminal.selectionBackground": "#0969da33",
      "terminal.ansiBlack": "#1f2328",
      "terminal.ansiRed": "#cf222e",
      "terminal.ansiGreen": "#1a7f37",
      "terminal.ansiYellow": "#9a6700",
      "terminal.ansiBlue": "#0969da",
      "terminal.ansiMagenta": "#cf222e",
      "terminal.ansiCyan": "#1b7c83",
      "terminal.ansiWhite": "#6e7781",
      "terminal.ansiBrightBlack": "#57606a",
      "terminal.ansiBrightRed": "#a40e26",
      "terminal.ansiBrightGreen": "#116329",
      "terminal.ansiBrightYellow": "#7d4e00",
      "terminal.ansiBrightBlue": "#0550ae",
      "terminal.ansiBrightMagenta": "#a40e26",
      "terminal.ansiBrightCyan": "#0c5d6a",
      "terminal.ansiBrightWhite": "#8c959f",
    },
    tokenColors: lightTokenColors,
    terminal: {
      background: "#ffffff",
      foreground: "#1f2328",
      cursor: "#0969da",
      cursorAccent: "#ffffff",
      selectionBackground: "#0969da33",
      black: "#1f2328",
      red: "#cf222e",
      green: "#1a7f37",
      yellow: "#9a6700",
      blue: "#0969da",
      magenta: "#cf222e",
      cyan: "#1b7c83",
      white: "#6e7781",
      brightBlack: "#57606a",
      brightRed: "#a40e26",
      brightGreen: "#116329",
      brightYellow: "#7d4e00",
      brightBlue: "#0550ae",
      brightMagenta: "#a40e26",
      brightCyan: "#0c5d6a",
      brightWhite: "#8c959f",
    },
  },
  {
    name: "catppuccin-mocha",
    type: "dark",
    colors: {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      "editor.lineHighlightBackground": "#313244",
      "editor.selectionBackground": "#585b70",
      "editorCursor.foreground": "#f5e0dc",
      "editorLineNumber.foreground": "#6c7086",
      "editorLineNumber.activeForeground": "#cdd6f4",
      "editorIndentGuide.background1": "#45475a",
      "editorIndentGuide.activeBackground1": "#585b70",
      "editorWidget.background": "#181825",
      "editorWidget.border": "#45475a",
      "editorSuggestWidget.background": "#181825",
      "editorSuggestWidget.border": "#45475a",
      "editorSuggestWidget.selectedBackground": "#313244",
      "terminal.background": "#1e1e2e",
      "terminal.foreground": "#cdd6f4",
      "terminal.cursor": "#f5e0dc",
      "terminal.cursorAccent": "#1e1e2e",
      "terminal.selectionBackground": "#585b70",
      "terminal.ansiBlack": "#45475a",
      "terminal.ansiRed": "#f38ba8",
      "terminal.ansiGreen": "#a6e3a1",
      "terminal.ansiYellow": "#f9e2af",
      "terminal.ansiBlue": "#89b4fa",
      "terminal.ansiMagenta": "#f5c2e7",
      "terminal.ansiCyan": "#94e2d5",
      "terminal.ansiWhite": "#bac2de",
      "terminal.ansiBrightBlack": "#585b70",
      "terminal.ansiBrightRed": "#f38ba8",
      "terminal.ansiBrightGreen": "#a6e3a1",
      "terminal.ansiBrightYellow": "#f9e2af",
      "terminal.ansiBrightBlue": "#89b4fa",
      "terminal.ansiBrightMagenta": "#f5c2e7",
      "terminal.ansiBrightCyan": "#94e2d5",
      "terminal.ansiBrightWhite": "#a6adc8",
    },
    tokenColors: catppuccinTokenColors,
    terminal: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      cursorAccent: "#1e1e2e",
      selectionBackground: "#585b70",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
  {
    name: "spiderman",
    type: "dark",
    colors: {
      "editor.background": "#0D111A",
      "editor.foreground": "#E8EDF2",
      "editor.lineHighlightBackground": "#151B28",
      "editor.selectionBackground": "#2B5BED44",
      "editorCursor.foreground": "#E23636",
      "editorLineNumber.foreground": "#4A5568",
      "editorLineNumber.activeForeground": "#E8EDF2",
      "editorIndentGuide.background1": "#1E2740",
      "editorIndentGuide.activeBackground1": "#2A3245",
      "editorWidget.background": "#151B28",
      "editorWidget.border": "#2A3245",
      "editorSuggestWidget.background": "#0F1520",
      "editorSuggestWidget.border": "#2A3245",
      "editorSuggestWidget.selectedBackground": "#2B5BED33",
      "terminal.background": "#0D111A",
      "terminal.foreground": "#E8EDF2",
      "terminal.cursor": "#E23636",
      "terminal.cursorAccent": "#0D111A",
      "terminal.selectionBackground": "#2B5BED44",
      "terminal.ansiBlack": "#1A1F2E",
      "terminal.ansiRed": "#E23636",
      "terminal.ansiGreen": "#2EA043",
      "terminal.ansiYellow": "#D29922",
      "terminal.ansiBlue": "#2B5BED",
      "terminal.ansiMagenta": "#BC3F8C",
      "terminal.ansiCyan": "#39C5CF",
      "terminal.ansiWhite": "#E8EDF2",
      "terminal.ansiBrightBlack": "#4A5568",
      "terminal.ansiBrightRed": "#F44336",
      "terminal.ansiBrightGreen": "#4CAF50",
      "terminal.ansiBrightYellow": "#FFC107",
      "terminal.ansiBrightBlue": "#5C7FEF",
      "terminal.ansiBrightMagenta": "#D45C9E",
      "terminal.ansiBrightCyan": "#64D8E3",
      "terminal.ansiBrightWhite": "#F5F8FC",
    },
    tokenColors: [],
    terminal: {
      background: "#0D111A",
      foreground: "#E8EDF2",
      cursor: "#E23636",
      cursorAccent: "#0D111A",
      selectionBackground: "#2B5BED44",
      black: "#1A1F2E",
      red: "#E23636",
      green: "#2EA043",
      yellow: "#D29922",
      blue: "#2B5BED",
      magenta: "#BC3F8C",
      cyan: "#39C5CF",
      white: "#E8EDF2",
      brightBlack: "#4A5568",
      brightRed: "#F44336",
      brightGreen: "#4CAF50",
      brightYellow: "#FFC107",
      brightBlue: "#5C7FEF",
      brightMagenta: "#D45C9E",
      brightCyan: "#64D8E3",
      brightWhite: "#F5F8FC",
    },
  },
];
