import {
  File,
  FileCode,
  FileJson,
  FileText,
  FileType,
  FileImage,
  Folder,
  FolderOpen,
  FileSpreadsheet,
  FileArchive,
  FileVideo,
  FileAudio,
  ScrollText,
  Database,
  Settings,
  Terminal,
  Braces,
  Lock,
  Container,
  type LucideIcon,
} from "lucide-react";
import type { IconPackDefinition } from "@/types/icons";

export const BUILTIN_ICON_REGISTRY: Record<string, LucideIcon> = {
  File,
  FileCode,
  FileJson,
  FileText,
  FileType,
  FileImage,
  Folder,
  FolderOpen,
  FileSpreadsheet,
  FileArchive,
  FileVideo,
  FileAudio,
  ScrollText,
  Database,
  Settings,
  Terminal,
  Braces,
  Lock,
  Container,
};

export const DEFAULT_ICON_PACK: IconPackDefinition = {
  name: "quantum-default",
  version: "1.0.0",
  icons: {
    // Filenames (checked first)
    "readme": "FileText",
    "license": "ScrollText",
    "makefile": "FileCode",
    "dockerfile": "Container",
    "gitignore": "FileCode",
    "env": "Settings",
    // Extensions
    "ts": "FileCode",
    "tsx": "FileCode",
    "js": "FileCode",
    "jsx": "FileCode",
    "mjs": "FileCode",
    "cjs": "FileCode",
    "rs": "FileCode",
    "py": "FileCode",
    "java": "FileCode",
    "rb": "FileCode",
    "go": "FileCode",
    "c": "FileCode",
    "cpp": "FileCode",
    "h": "FileCode",
    "hpp": "FileCode",
    "kt": "FileCode",
    "kts": "FileCode",
    "swift": "FileCode",
    "dart": "FileCode",
    "ex": "FileCode",
    "exs": "FileCode",
    "nim": "FileCode",
    "zig": "FileCode",
    "html": "FileCode",
    "css": "FileCode",
    "scss": "FileCode",
    "less": "FileCode",
    "yaml": "FileCode",
    "yml": "FileCode",
    "sh": "Terminal",
    "bash": "Terminal",
    "zsh": "Terminal",
    "fish": "Terminal",
    "json": "FileJson",
    "jsonc": "FileJson",
    "md": "FileText",
    "mdx": "FileText",
    "txt": "FileText",
    "log": "FileText",
    "pdf": "FileText",
    "doc": "FileText",
    "docx": "FileText",
    "sql": "Database",
    "db": "Database",
    "prisma": "Database",
    "xls": "FileSpreadsheet",
    "xlsx": "FileSpreadsheet",
    "csv": "FileSpreadsheet",
    "tsv": "FileSpreadsheet",
    "png": "FileImage",
    "jpg": "FileImage",
    "jpeg": "FileImage",
    "gif": "FileImage",
    "svg": "FileImage",
    "webp": "FileImage",
    "ico": "FileImage",
    "bmp": "FileImage",
    "zip": "FileArchive",
    "tar": "FileArchive",
    "gz": "FileArchive",
    "rar": "FileArchive",
    "7z": "FileArchive",
    "mp4": "FileVideo",
    "avi": "FileVideo",
    "mkv": "FileVideo",
    "mov": "FileVideo",
    "webm": "FileVideo",
    "mp3": "FileAudio",
    "wav": "FileAudio",
    "ogg": "FileAudio",
    "flac": "FileAudio",
    "toml": "Settings",
    "ini": "Settings",
    "cfg": "Settings",
    "conf": "Settings",
    "gradle": "Settings",
    "lock": "Lock",
    "xml": "Braces",
    "vue": "Braces",
    "svelte": "Braces",
    "astro": "Braces",
    "graphql": "Braces",
    "gql": "Braces",
    "folder": "Folder",
    "folderOpen": "FolderOpen",
    "fileDefault": "File",
    "fileUnknown": "FileType",
  },
};
