use super::SwarmError;
use std::collections::HashMap;
use std::path::PathBuf;

/// Provider → env-var mapping (design Section 7.3)
pub const PROVIDER_ENV_MAP: &[(&str, &str)] = &[
    ("deepseek", "DEEPSEEK_API_KEY"),
    ("openai", "OPENAI_API_KEY"),
    ("anthropic", "ANTHROPIC_API_KEY"),
    ("openrouter", "OPENROUTER_API_KEY"),
];

/// Get the env var name for a provider.
pub fn provider_to_env_var(provider: &str) -> Option<&'static str> {
    PROVIDER_ENV_MAP
        .iter()
        .find(|(p, _)| p == &provider)
        .map(|(_, env)| *env)
}

/// Build the secrets file path from project root.
fn secrets_path(project_root: &str) -> PathBuf {
    PathBuf::from(project_root).join(".quantum").join(".secrets.env")
}

/// Read all API keys from `.quantum/.secrets.env`.
fn read_secrets(project_root: &str) -> Result<HashMap<String, String>, SwarmError> {
    let path = secrets_path(project_root);
    if !path.exists() {
        return Ok(HashMap::new());
    }
    let content = std::fs::read_to_string(&path)?;
    let mut secrets = HashMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            secrets.insert(key.trim().to_string(), value.trim().to_string());
        }
    }
    Ok(secrets)
}

/// Write all API keys to `.quantum/.secrets.env`.
fn write_secrets(project_root: &str, secrets: &HashMap<String, String>) -> Result<(), SwarmError> {
    let path = secrets_path(project_root);

    // Ensure .quantum directory exists
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut content = String::new();
    content.push_str("# Quantum Swarm API Keys\n");
    content.push_str("# Generated by IDE. Do not edit manually.\n\n");
    let mut keys: Vec<_> = secrets.keys().collect();
    keys.sort();
    for key in keys {
        if let Some(value) = secrets.get(key) {
            content.push_str(&format!("{}={}\n", key, value));
        }
    }

    std::fs::write(&path, &content)?;

    // Set permissions to 600 on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))?;
    }

    Ok(())
}

/// Get an API key for a provider.
pub fn get_api_key(project_root: &str, provider: &str) -> Result<Option<String>, SwarmError> {
    let secrets = read_secrets(project_root)?;
    Ok(secrets.get(provider).cloned())
}

/// Set an API key for a provider.
pub fn set_api_key(project_root: &str, provider: &str, key: &str) -> Result<(), SwarmError> {
    let mut secrets = read_secrets(project_root)?;
    secrets.insert(provider.to_string(), key.to_string());
    write_secrets(project_root, &secrets)
}

/// Delete an API key for a provider.
pub fn delete_api_key(project_root: &str, provider: &str) -> Result<(), SwarmError> {
    let mut secrets = read_secrets(project_root)?;
    secrets.remove(provider);
    write_secrets(project_root, &secrets)
}

/// Build environment variables for an agent spawn.
/// Includes QUANTUM_* vars and provider API keys.
pub fn build_agent_env(
    project_root: &str,
    agent_id: &str,
    agent_type: &str,
    model: &str,
    swarm_id: &str,
) -> Result<Vec<(String, String)>, SwarmError> {
    let worktree = format!("{}/.quantum/worktrees/{}", project_root, agent_id);
    let agent_dir = format!("{}/.quantum/agents/{}", project_root, agent_id);
    let branch = format!("swarm/{}", agent_id);

    let mut env_vars = Vec::new();

    // QUANTUM_* env vars
    env_vars.push(("QUANTUM_AGENT_ID".into(), agent_id.to_string()));
    env_vars.push(("QUANTUM_AGENT_DIR".into(), agent_dir));
    env_vars.push(("QUANTUM_WORKTREE".into(), worktree));
    env_vars.push(("QUANTUM_PROJECT_ROOT".into(), project_root.to_string()));
    env_vars.push(("QUANTUM_BRANCH".into(), branch));
    env_vars.push(("QUANTUM_SWARM_ID".into(), swarm_id.to_string()));
    env_vars.push(("QUANTUM_AGENT_TYPE".into(), agent_type.to_string()));
    env_vars.push(("QUANTUM_MODEL".into(), model.to_string()));

    // Provider API keys
    let secrets = read_secrets(project_root)?;
    for (provider, env_var) in PROVIDER_ENV_MAP {
        if let Some(key) = secrets.get(*provider) {
            env_vars.push((env_var.to_string(), key.clone()));
        }
    }

    Ok(env_vars)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_provider_env_mapping() {
        assert_eq!(provider_to_env_var("deepseek"), Some("DEEPSEEK_API_KEY"));
        assert_eq!(provider_to_env_var("openai"), Some("OPENAI_API_KEY"));
        assert_eq!(provider_to_env_var("unknown"), None);
    }

    #[test]
    fn test_set_get_delete_key() {
        let dir = tempfile::TempDir::new("swarm-keyring-test").unwrap();
        let root = dir.path().to_str().unwrap().to_string();

        // Initially empty
        assert_eq!(get_api_key(&root, "deepseek").unwrap(), None);

        // Set key
        set_api_key(&root, "deepseek", "sk-test-123").unwrap();
        assert_eq!(
            get_api_key(&root, "deepseek").unwrap(),
            Some("sk-test-123".to_string())
        );

        // Delete key
        delete_api_key(&root, "deepseek").unwrap();
        assert_eq!(get_api_key(&root, "deepseek").unwrap(), None);
    }

    #[test]
    fn test_build_agent_env() {
        let dir = tempfile::TempDir::new("swarm-env-test").unwrap();
        let root = dir.path().to_str().unwrap().to_string();

        set_api_key(&root, "deepseek", "sk-ds-key").unwrap();

        let env_vars = build_agent_env(&root, "agent-1", "opencode", "deepseek-v4-flash-free", "swarm_test")
            .unwrap();

        let map: HashMap<String, String> = env_vars.into_iter().collect();
        assert_eq!(map.get("QUANTUM_AGENT_ID").unwrap(), "agent-1");
        assert_eq!(map.get("QUANTUM_AGENT_TYPE").unwrap(), "opencode");
        assert_eq!(map.get("QUANTUM_MODEL").unwrap(), "deepseek-v4-flash-free");
        assert_eq!(map.get("QUANTUM_SWARM_ID").unwrap(), "swarm_test");
        assert_eq!(map.get("QUANTUM_WORKTREE").unwrap(), &format!("{}/.quantum/worktrees/agent-1", root));
        assert_eq!(map.get("DEEPSEEK_API_KEY").unwrap(), "sk-ds-key");
    }
}
